# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "ohci_pci" "ehci_pci" "ahci" "firewire_ohci" "usb_storage" "usbhid" ];
  boot.kernelModules = [ "kvm-intel" "wl" ];
  boot.extraModulePackages = [ config.boot.kernelPackages.broadcom_sta ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/9aa7fb10-6cf3-40af-8098-429d44197008";
      fsType = "ext4";
    };
  fileSystems."/".options = [ "defaults" "noatime" "discard"];

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/3CA4-F723";
      fsType = "vfat";
    };
  fileSystems."/boot".options = ["defaults" "noatime" "discard"];

  # Use the gummiboot efi boot loader.
  boot.loader.gummiboot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;
  boot.initrd.luks.devices = [{
    name = "luksroot"; device = "/dev/sdb2";
  }];
  boot.tmpOnTmpfs = true;
  boot.kernel.sysctl = { "vm.swappiness" = 10; }; #SSD OPTIMIZATION

  swapDevices = [ {
    device = "/var/swap";
    size = 4096;
  } ];

  nix.maxJobs = 2;

  networking.hostId = "7ba8afd9";
  networking.hostName = "thallmbp"; # Define your hostname.
  networking.wireless.driver = "wext"; #MBP2009 specific

  hardware.opengl = {
    extraPackages = with pkgs; [ vaapiVdpau ];
    driSupport = true;
    driSupport32Bit = true;
  };

  services.xserver = {
    synaptics.additionalOptions = ''
        Option "TapButton1" "0"
        Option "TapButton2" "0"
        Option "TapButton3" "0"
        '';
    deviceSection = ''
      Option "NoLogo" "true"
      '';
    videoDrivers = [ "nvidiaLegacy340" ];
  };
}
