# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];
  boot.blacklistedKernelModules = [ "psmouse"];
  boot.kernelPackages = pkgs.linuxPackages_latest;

  # Docker broken with systemd 232
  # https://github.com/docker/docker/issues/28109
  # https://github.com/opencontainers/runc/issues/1175
  # https://github.com/NixOS/nixpkgs/issues/22472
  boot.kernelParams = ["systemd.legacy_systemd_cgroup_controller=yes"];

  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/ca317ca3-ff9c-4f57-965e-8897435b0c36";
      fsType = "ext4";
      options = ["noatime" "nodiratime" "discard"];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/9166-6F5F";
      fsType = "vfat";
    };
  boot.initrd.luks.devices = [{ name = "luksroot"; device = "/dev/nvme0n1p2"; allowDiscards = true; }];

  boot.tmpOnTmpfs = true;
  boot.kernel.sysctl = { "vm.swappiness" = 10; "vm.max_map_count" = 262144; }; #SSD OPTIMIZATION

  swapDevices = [ {
    device = "/var/swap";
    size = 4096;
  } ];

  services.xserver = {
    videoDrivers = [ "intel" ];
  };

  hardware.opengl.extraPackages = with pkgs; [ vaapiIntel ];

  nix.maxJobs = lib.mkDefault 1;
}
