# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  hardware.cpu.amd.updateMicrocode = true;
  hardware.bluetooth.enable = true;

  boot = {
    initrd = {
      availableKernelModules = [ "nvme" "ehci_pci" "xhci_pci" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
      kernelModules = [ "amdgpu" ];
    };
    kernelModules = [ "kvm-amd" ];
    kernelPackages = pkgs.linuxPackages_5_15;
    extraModulePackages = [ ];
  };

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/94903bb8-9085-45d2-9a88-1dec5486546e";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."crypted".device = "/dev/disk/by-uuid/f6b03ffa-6f25-4e58-926a-7d1537429077";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/68E0-3015";
      fsType = "vfat";
    };

  swapDevices = [ 
   { device = "/var/swapfile"; }
  ];
}

